/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import javax.swing.JOptionPane;


public class Pilihan extends javax.swing.JFrame {

    /**
     * Creates new form Pilihan
     */
    public Pilihan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        almarhumButton = new javax.swing.JButton();
        keluargaButton = new javax.swing.JButton();
        tombollogout = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        almarhumButton.setText("Manajemen Data Almarhum");
        almarhumButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                almarhumButtonMouseClicked(evt);
            }
        });
        almarhumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                almarhumButtonActionPerformed(evt);
            }
        });
        getContentPane().add(almarhumButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 200, 70));

        keluargaButton.setText("Manajemen Data Keluarga Almarhum");
        keluargaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keluargaButtonMouseClicked(evt);
            }
        });
        getContentPane().add(keluargaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 260, 70));

        tombollogout.setText("LOGOUT");
        tombollogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombollogoutActionPerformed(evt);
            }
        });
        getContentPane().add(tombollogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, -1, -1));

        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\mhddi\\Videos\\datakematian\\datakematian\\resources\\images\\2.png")); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void keluargaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keluargaButtonMouseClicked
        new KeluargaCRUD().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_keluargaButtonMouseClicked

    private void almarhumButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_almarhumButtonMouseClicked
        new AlmarhumCRUD().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_almarhumButtonMouseClicked

    private void almarhumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_almarhumButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_almarhumButtonActionPerformed

    private void tombollogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombollogoutActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(null, "Anda yakin ingin logout?", "Konfirmasi Logout", JOptionPane.YES_NO_OPTION);
    
        if (choice == JOptionPane.YES_OPTION) {
            // Pilihan "Ya," maka lakukan logout dan kembali ke halaman Login.java
            new Login().setVisible(true);
            this.dispose();
        } else {
        // Pilihan "Tidak" atau tombol close di dialog konfirmasi, tidak melakukan apa-apa.
    }
    }//GEN-LAST:event_tombollogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pilihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pilihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pilihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pilihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pilihan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton almarhumButton;
    private javax.swing.JLabel background;
    private javax.swing.JButton keluargaButton;
    private javax.swing.JButton tombollogout;
    // End of variables declaration//GEN-END:variables
}
